version: "3"

services:
  flask:
    restart: always
    build: .
    container_name: scraper
    ports:
      - "5000:5000"
    command: >
      sh -c "python run.py"
    env_file:
      - .env
    volumes:
      - .:/scraper
